steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-7910093f-7276-4858-97d/shapeasy-repo/shopeasy-app:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-7910093f-7276-4858-97d/shapeasy-repo/shopeasy-app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/project-7910093f-7276-4858-97d/shapeasy-repo/shopeasy-app'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'get-credentials'
    args: ['cluster-info']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=private-gke'
    waitFor: ['push-image']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'apply-k8s'
    args: ['apply', '-f', 'k8s/frontend-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=private-gke'
    waitFor: ['get-credentials']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'rollout'
    args:
      - 'set'
      - 'image'
      - 'deployment/shopeasy-app'
      - 'shopeasy-app=us-central1-docker.pkg.dev/project-7910093f-7276-4858-97d/shapeasy-repo/shopeasy-app:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=private-gke'
    waitFor: ['apply-k8s']

images:
  - 'us-central1-docker.pkg.dev/project-7910093f-7276-4858-97d/shapeasy-repo/shopeasy-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
