name: CI - Build and Push Image

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/291021065165/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
          service_account: github-actions-deployer@sanjuktha-501709.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and push image
        run: |
          docker build -t asia-south1-docker.pkg.dev/sanjuktha-501709/my-app-repo/my-app:${{ github.sha }} .
          docker push asia-south1-docker.pkg.dev/sanjuktha-501709/my-app-repo/my-app:${{ github.sha }}

      - name: Update deployment manifest with new image tag
        run: |
          sed -i "s|image: .*|image: asia-south1-docker.pkg.dev/sanjuktha-501709/my-app-repo/my-app:${{ github.sha }}|" k8s/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "[email protected]"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          git push

          
